ansible

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -1,14 +1,14 @@
 # Use the latest 2.1 version of CircleCI pipeline process engine.
 # See: https://circleci.com/docs/2.0/configuration-reference
 version: 2.1
-commands:
-  print_pipeline_id:
-    description: "A command to print the Circle CI Workflow ID"
-    steps:
-      - run:
-          name: "Print the Circle CI Workflow ID"
-          command: |
-            echo $CIRCLE_WORKFLOW_ID
+# commands:
+#   print_pipeline_id:
+#     description: "A command to print the Circle CI Workflow ID"
+#     steps:
+#       - run:
+#           name: "Print the Circle CI Workflow ID"
+#           command: |
+#             echo $CIRCLE_WORKFLOW_ID
 
 # Define a job to be invoked later in a workflow.
 # See: https://circleci.com/docs/2.0/configuration-reference/#jobs
@@ -47,56 +47,89 @@ jobs:
   #         command: |
   #           echo $USERNAME
   
-  save_hello_world_output:
+  # save_hello_world_output:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: "save an output to a file"
+  #         command: |
+  #           echo "hello world" > ~/output.txt 
+  #     - persist_to_workspace:
+  #         root: ~/
+  #         paths:
+  #           - output.txt 
+
+  # print_output_file:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout 
+  #     - attach_workspace:
+  #         at: ~/
+  #     - run:
+  #         name: "retrieve an output from a file"
+  #         command: |
+  #           cat ~/output.txt
+
+  # command_test:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - print_pipeline_id
+    
+  # failure:
+  #   docker:
+  #     - image: circleci/node:13.8.0
+  #   steps:
+  #     - checkout
+  #     - run:
+  #         name: "Fail intentionally"
+  #         command: |
+  #           exit 1
+            
+  #     - run:
+  #         name: "Do this on fail"
+  #         command: |
+  #           echo "Pipeline has failed!"
+  #         when: on_fail
+  
+  inventory:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout
       - run:
-          name: "save an output to a file"
+          name: "Add [all] to inventory"
           command: |
-            echo "hello world" > ~/output.txt 
+            echo "[all]" > /etc/ansible/inventory 
+      - run:
+          name: "Add Public IP to inventory"
+          command: |
+            aws ec2 describe-instances \
+            \
+                    --query 'Reservations[*].Instances[*].PublicIpAddress' \
+                  --filters "Name=tag:Project,Values=udacity" \
+                  --output text >> /etc/ansible/inventory
       - persist_to_workspace:
-          root: ~/
+          root: /etc.ansible
           paths:
-            - output.txt 
+            - inventory
 
-  print_output_file:
+  print_inventory:
     docker:
       - image: circleci/node:13.8.0
     steps:
       - checkout 
       - attach_workspace:
-          at: ~/
+          at: /etc/ansible
       - run:
           name: "retrieve an output from a file"
           command: |
-            cat ~/output.txt
-
-  command_test:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - print_pipeline_id
-    
-  failure:
-    docker:
-      - image: circleci/node:13.8.0
-    steps:
-      - checkout
-      - run:
-          name: "Fail intentionally"
-          command: |
-            exit 1
-            
-      - run:
-          name: "Do this on fail"
-          command: |
-            echo "Pipeline has failed!"
-          when: on_fail
-     
-     
+            cat etc/ansible/inventory
+  
 
 # Invoke jobs via workflows
 # See: https://circleci.com/docs/2.0/configuration-reference/#workflows
@@ -108,13 +141,16 @@ workflows:
       #     requires: [print_hello]
       # - print_name:
       #     requires: [print_hello,print_world]
-      - save_hello_world_output
-      - print_output_file:
-          requires: [save_hello_world_output]
-      - command_test:
-          requires: [print_output_file]
-      - failure:
-          requires: [command_test]
+      # - save_hello_world_output
+      # - print_output_file:
+      #     requires: [save_hello_world_output]
+      # - command_test:
+      #     requires: [print_output_file]
+      # - failure:
+      #     requires: [command_test]
+      -inventory
+      -print_inventory:
+          requires: [inventory]
         
            
           
